### PR TITLE
Added support for ae2 rv6-alpha-4

### LINKED ISSUE #578: AE2 rv6 API breaking changes
https://paste.dimdev.org/zukidifira.mccrash

ExtraCells-1.12.2-2.5.13a60
 Forge 14.23.4.2735

EDIT(by ruifung): For anyone having crashes with ExtraCells-1.12.2-2.5.13 (latest on curseforge at this time), please do check if you are running AE2 RV6 ALPHA. There's been a bunch of API breaks in AE2 RV6. At this point in time (20/06/2018) AE2 RV6 is still in ALPHA.

### PR DESCRIPTION
**Pull request by BrockWS**
Closes #578

### CODE REVIEW

**Comment by BrockWS** [comment]
Maybe I should push to rv5 branch instead

**Comment by BrockWS** [comment]
Waiting for alpha 4

**Comment by CarlucciMods** [comment]
You closed my post and it's fine but I'm on RV 6 beta 1

**Comment by BrockWS** [comment]
RV6-alpha-4 == RV6-beta-1 as only a small bugfix was done for rv6-beta-1. These fixes *should* be compatible with rv6-alpha-4, rv6-beta-1 and future rv6 versions.

**Comment by CarlucciMods** [comment]
where can i download the new update ? Please and Thank you

**Pull request merged**
