### PR TITLE
Multiple improvements and fixes for gas integration 

### LINKED ISSUE #520: Gas level emitter GUI displays and behave as fluid level emitter
Hey there,

I play the "all the mods 3" modpack and I have a strange problem with the gas level emitter. After crafting the emitter it displays as Gas level emitter, but if I put it on a ME cable an open the emitter the GUI displays a fluid level emitter and it bahaves like one. I hope you have a solution for that problem.

### LINKED ISSUE #617: ME Gas Level Emitter is behaving like ME Liquid Level Emitter but with a different GUI
o/

The ME Gas Level Emitter is like ME Liquid Level Emitter: you can set it up for any liquid (and it will work for that liquid), but not for gasses like intended.

Versions:
AE2: appliedenergistics2-rv6-stable-3
ExtraCells2: ExtraCells-1.12.2-2.6.1a

image
image

_Originally posted by @nowifi4u in https://github.com/ExtraCells/ExtraCells2/issues/606#issuecomment-444644445_

### LINKED ISSUE #688: ME Gas Terminal Will only display the Gas Amount From one cell at a time.
Minecraft Version: 1.12.2
Extra Cells 2 Version: 2.6.5
Forge Version: 14.23.5.2847
Applied Energistics 2 Version: rv6-stable-7
 
Cell's in Position 3-5 are completely empty.
Cell 1 has: 
Cell 1 is 64K Gas Cell
Cell 2 is 4096K Gas Cell

With Cell 1 & 2 In:  
image
image

With Cell 2 In:
image
image

I did not get a picture but with 2 in and 1 Out it displays the same as with 1 & 2 in.

### PR DESCRIPTION
**Pull request by ElektroKill**
Hello, I did some fixes to the Mekanism gas integration.
* Fixed Gas Level Emitter behavior (fixes #617, fixes #520)
* Fixed Gas Terminal showing incorrect amount of gas (fixes #688)
* Fixed rendering of gases in GUIs, the gases where all white beforehand.
* Fixes hwyla dependency

I hope you are able to merge this and pushing update to CurseForge!
Thanks in advance!

### CODE REVIEW

**Review by CoolCat467 — APPROVED** [review]
Yes

**Review by CoolCat467 — APPROVED** [review]
I wonder why else wasn't there in the first place

**Comment by SamLam140330** [comment]
> Hello, I did some fixes to the Mekanism gas integration.
> 
> * Fixed Gas Level Emitter behavior (fixes #617, fixes #520)
> * Fixed Gas Terminal showing incorrect amount of gas (fixes #688)
> * Fixed rendering of gases in GUIs, the gases where all white beforehand.
> * Fixes hwyla dependency
> 
> I hope you are able to merge this and pushing update to CurseForge!
> Thanks in advance!

Hello, Could I use it in my forked version?

**Comment by ryuujo1573** [comment]
Wow, it's so nice of you to do such work!
I was just wondering how could I report this and noticed that the project had been marked as unmaintained in CurseForge, which was sad :(

image
[A "gas" emitter] 

I can't wait to patch this fix to my current modpack

**Comment by ryuujo1573** [comment]
and... if it is convenient for you, could you please give me some hints on **how to build this proj** and get a proper `.jar` for the minecraft?

**Comment by ryuujo1573** [comment]
```
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve cofh:RedstoneFlux:1.12-+.
     Required by:
         project :
      > Failed to list versions for cofh:RedstoneFlux.
         > Unable to load Maven meta-data from https://maven.tehnut.info/cofh/RedstoneFlux/maven-metadata.xml.
            > Could not get resource 'https://maven.tehnut.info/cofh/RedstoneFlux/maven-metadata.xml'.
               > Could not GET 'https://maven.tehnut.info/cofh/RedstoneFlux/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for cofh:RedstoneFlux.
         > Unable to load Maven meta-data from https://minecraft.curseforge.com/api/maven/cofh/RedstoneFlux/maven-metadata.xml.
            > Could not get resource 'https://minecraft.curseforge.com/api/maven/cofh/RedstoneFlux/maven-metadata.xml'.
               > Could not GET 'https://minecraft.curseforge.com/api/maven/cofh/RedstoneFlux/maven-metadata.xml'. Received status code 503 from server: Service Temporarily Unavailable
   > Could not resolve mekanism:Mekanism:1.12.2.
     Required by:
         project :
      > Could not resolve mekanism:Mekanism:1.12.2.
         > Could not get resource 'https://maven.tehnut.info/mekanism/Mekanism/1.12.2/Mekanism-1.12.2.pom'.
            > Could not GET 'https://maven.tehnut.info/mekanism/Mekanism/1.12.2/Mekanism-1.12.2.pom'. Received status code 403 from server: Forbidden
      > Skipped due to earlier error
```

It seems that the `maven.tehnut.info` has been down, how could I fix this

**Pull request merged**
