### PR TITLE
Fixed WCT integration and recipe. Fixes #619

### LINKED ISSUE #619: Crash With WCT + AE2WTLib + Baubles
Extra Cells: 2.6.1a
Wireless Crafting Terminal: 3.11.83
AE2WTLib: 1.0.2 (New library for WCT that is required for the new version of WCT)
Baubles: 1.5.2
AE2: RV6 Stable 4
Forge: 2776

Integration option in Extra Cells for WCT has been tried with it on and off. Reverting WCT version will not result in crash.

https://paste.ee/p/ijXXQ

### PR DESCRIPTION
**Pull request by BrockWS**

### CODE REVIEW

**Comment by BrockWS** [comment]
@Nedelosk Can you merge these and upload as 2.6.2 please?
Changelog:
Fixed WCT integration and universal crafting terminal recipe (Fixes #619)
Fixed issue with gas io bus capability issue with scala (Fixes #614)
AE2 Fluid Term can now be used in UniTerm recipe (Fixes #612)
Fixed Gas Storage Bus Name (Fixes #606)
Use chestWood for recipe (Fixes #621)

**Comment by ImAK9** [comment]
@BrockWS Any chance you could Jar it and send it to me as Nedelosk haven't been active this month...

**Comment by BrockWS** [comment]
You can use the jar here. https://ci.brock.pw/job/ExtraCells2/job/ExtraCells2-PRs/5/

**Comment by ruifung** [comment]
@BrockWS Merged all fixes, can't do anything about the curseforge release tho.

**Comment by BrockWS** [comment]
Thank you :)

**Pull request merged**
